config/routes.rb
      resources :lists, only: :index, controller: :lists
      resources :domain_blocks, only: :index, controller: :blocked_domains
    end

    resource :two_factor_authentication, only: [:show, :create, :destroy]

    namespace :two_factor_authentication do
      resources :recovery_codes, only: [:create]
      resource :confirmation, only: [:new, :create]
    end

    resources :identity_proofs, only: [:index, :show, :new, :create, :update]

    resources :applications, except: [:edit] do
      member do
        post :regenerate
      end
    end

    resources :flavours, only: [:index, :show, :update], param: :flavour

    resource :delete, only: [:show, :destroy]
    resource :migration, only: [:show, :update]

    resources :sessions, only: [:destroy]
    resources :featured_tags, only: [:index, :create, :destroy]
  end

  resources :media, only: [:show] do
    get :player
  end

  resources :tags,   only: [:show]
  resources :emojis, only: [:show]
  resources :invites, only: [:index, :create, :destroy]
  resources :filters, except: [:show]
  resource :relationships, only: [:show, :update]

  get '/public', to: 'public_timelines#show', as: :public_timeline
  get '/media_proxy/:id/(*any)', to: 'media_proxy#show', as: :media_proxy

  # Remote follow
  resource :remote_unfollow, only: [:create]
  resource :authorize_interaction, only: [:show, :create]
  resource :share, only: [:show, :create]

  namespace :admin do
    get '/dashboard', to: 'dashboard#index'

    resources :subscriptions, only: [:index]
    resources :domain_blocks, only: [:new, :create, :show, :destroy]
    resources :email_domain_blocks, only: [:index, :new, :create, :destroy]
    resources :action_logs, only: [:index]
    resources :warning_presets, except: [:new]
    resource :settings, only: [:edit, :update]

    resources :invites, only: [:index, :create, :destroy] do
      collection do
        post :deactivate_all
      end
    end

    resources :relays, only: [:index, :new, :create, :destroy] do
      member do
        post :enable
        post :disable
      end
    end

    resources :instances, only: [:index, :show], constraints: { id: /[^\/]+/ }

    resources :reports, only: [:index, :show] do
      member do
        post :assign_to_self
        post :unassign
        post :reopen
        post :resolve
      end

      resources :reported_statuses, only: [:create]
    end

    resources :report_notes, only: [:create, :destroy]

    resources :accounts, only: [:index, :show] do
      member do
        post :subscribe
        post :unsubscribe
        post :enable
        post :unsilence
        post :unsuspend
        post :redownload
        post :remove_avatar
        post :remove_header
        post :memorialize
        post :approve
        post :reject
      end

      resource :change_email, only: [:show, :update]
      resource :reset, only: [:create]
      resource :action, only: [:new, :create], controller: 'account_actions'
      resources :statuses, only: [:index, :show, :create, :update, :destroy]
      resources :followers, only: [:index]

      resource :confirmation, only: [:create] do
        collection do
          post :resend
        end
      end

      resource :role do
        member do
          post :promote
          post :demote
        end
      end
    end

    resources :pending_accounts, only: [:index] do
      collection do
        post :approve_all
        post :reject_all
        post :batch
      end
    end

    resources :users, only: [] do
      resource :two_factor_authentication, only: [:destroy]
    end

    resources :custom_emojis, only: [:index, :new, :create, :update, :destroy] do
      member do
        post :copy
        post :enable
        post :disable
      end
    end

    resources :account_moderation_notes, only: [:create, :destroy]

    resources :tags, only: [:index] do
      member do
        post :hide
        post :unhide
      end
    end
  end

  get '/admin', to: redirect('/admin/dashboard', status: 302)

  namespace :api do
    # PubSubHubbub outgoing subscriptions
    resources :subscriptions, only: [:show]
    post '/subscriptions/:id', to: 'subscriptions#update'

    # PubSubHubbub incoming subscriptions
    post '/push', to: 'push#update', as: :push

    # Salmon
    post '/salmon/:id', to: 'salmon#update', as: :salmon

    # OEmbed
    get '/oembed', to: 'oembed#show', as: :oembed

    # Identity proofs
    get :proofs, to: 'proofs#index'

    # JSON / REST API
    namespace :v1 do
      resources :statuses, only: [:create, :show, :destroy] do
        scope module: :statuses do
          resources :reblogged_by, controller: :reblogged_by_accounts, only: :index
          resources :favourited_by, controller: :favourited_by_accounts, only: :index
          resource :reblog, only: :create
          post :unreblog, to: 'reblogs#destroy'

          resource :favourite, only: :create
          post :unfavourite, to: 'favourites#destroy'

          resource :bookmark, only: :create
          post :unbookmark, to: 'bookmarks#destroy'

          resource :mute, only: :create
          post :unmute, to: 'mutes#destroy'

          resource :pin, only: :create
          post :unpin, to: 'pins#destroy'
        end

        member do
          get :context
          get :card
        end
      end

      namespace :timelines do
        resource :direct, only: :show, controller: :direct
        resource :home, only: :show, controller: :home
        resource :public, only: :show, controller: :public
        resources :tag, only: :show
        resources :list, only: :show
      end

      resources :streaming, only: [:index]
      resources :custom_emojis, only: [:index]
      resources :suggestions, only: [:index, :destroy]
      resources :scheduled_statuses, only: [:index, :show, :update, :destroy]
      resources :preferences, only: [:index]

      resources :conversations, only: [:index, :destroy] do
        member do
          post :read
        end
      end

      get '/search', to: 'search#index', as: :search

      resources :follows,      only: [:create]
      resources :media,        only: [:create, :update]
      resources :blocks,       only: [:index]
      resources :mutes,        only: [:index] do
        collection do
          get 'details'
        end
      end
      resources :favourites,   only: [:index]
      resources :bookmarks,    only: [:index]
      resources :reports,      only: [:create]
      resources :filters,      only: [:index, :create, :show, :update, :destroy]
      resources :endorsements, only: [:index]

      namespace :apps do
        get :verify_credentials, to: 'credentials#show'
      end

      resources :apps, only: [:create]

      resource :instance, only: [:show] do
        resources :peers, only: [:index], controller: 'instances/peers'
        resource :activity, only: [:show], controller: 'instances/activity'
      end

      resource :domain_blocks, only: [:show, :create, :destroy]

      resources :follow_requests, only: [:index] do
        member do
          post :authorize
          post :reject
        end
      end

      resources :notifications, only: [:index, :show, :destroy] do
        collection do
          post :clear
          post :dismiss # Deprecated
          delete :destroy_multiple
        end

        member do
          post :dismiss
        end
      end

      namespace :accounts do
        get :verify_credentials, to: 'credentials#show'
        patch :update_credentials, to: 'credentials#update'
        resource :search, only: :show, controller: :search
        resources :relationships, only: :index
      end

      resources :accounts, only: [:create, :show] do
        resources :statuses, only: :index, controller: 'accounts/statuses'
        resources :followers, only: :index, controller: 'accounts/follower_accounts'
        resources :following, only: :index, controller: 'accounts/following_accounts'
        resources :lists, only: :index, controller: 'accounts/lists'
        resources :identity_proofs, only: :index, controller: 'accounts/identity_proofs'

        member do
          post :follow
          post :unfollow
          post :block
          post :unblock
          post :mute
          post :unmute
        end

        resource :pin, only: :create, controller: 'accounts/pins'
        post :unpin, to: 'accounts/pins#destroy'
      end

      resources :lists, only: [:index, :create, :show, :update, :destroy] do
        resource :accounts, only: [:show, :create, :destroy], controller: 'lists/accounts'
      end

      resources :polls, only: [:create, :show] do
        resources :votes, only: :create, controller: 'polls/votes'
      end

      namespace :push do
        resource :subscription, only: [:create, :show, :update, :destroy]
      end

      namespace :admin do
        resources :accounts, only: [:index, :show] do
          member do
            post :enable
            post :unsilence
            post :unsuspend
            post :approve
            post :reject
          end

          resource :action, only: [:create], controller: 'account_actions'
        end

        resources :reports, only: [:index, :show] do
          member do
            post :assign_to_self
            post :unassign
            post :reopen
            post :resolve
          end
        end
      end
    end

    namespace :v2 do
      get '/search', to: 'search#index', as: :search
    end

    namespace :web do
      resource :settings, only: [:update]
      resource :embed, only: [:create]
      resources :push_subscriptions, only: [:create] do
        member do
          put :update
        end
      end
    end
  end

  get '/web/(*any)', to: 'home#index', as: :web

  get '/about',      to: 'about#show'
  get '/about/more', to: 'about#more'
  get '/terms',      to: 'about#terms'

  root 'home#index'

  match '*unmatched_route',
        via: :all,
        to: 'application#raise_not_found',

app/controllers/about_controller.rb
# frozen_string_literal: true

class AboutController < ApplicationController
  before_action :set_pack
  layout 'public'

  before_action :set_instance_presenter, only: [:show, :more, :terms]

  def show
    @hide_navbar = true
  end

  def more; end

  def terms; end

  private

  def new_user
    User.new.tap do |user|
      user.build_account
      user.build_invite_request
    end
  end

  helper_method :new_user

  def set_pack
    use_pack 'common'
  end

  def set_instance_presenter
    @instance_presenter = InstancePresenter.new
  end
end

app/views/about/_login.html.haml
= simple_form_for(new_user, url: user_session_path) do |f|
  .fields-group
    - if use_seamless_external_login?
      = f.input :email, placeholder: t('simple_form.labels.defaults.username_or_email'), input_html: { 'aria-label' => t('simple_form.labels.defaults.username_or_email') }, hint: false
    - else
      = f.input :email, placeholder: t('simple_form.labels.defaults.email'), input_html: { 'aria-label' => t('simple_form.labels.defaults.email') }, hint: false

    = f.input :password, placeholder: t('simple_form.labels.defaults.password'), input_html: { 'aria-label' => t('simple_form.labels.defaults.password') }, hint: false

  .actions
    = f.button :button, t('auth.login'), type: :submit, class: 'button button-primary'

  %p.hint.subtle-hint= link_to t('auth.trouble_logging_in'), new_user_password_path

app/views/about/_registration.html.haml
= simple_form_for(new_user, url: user_registration_path) do |f|
  .simple_form__overlay-area
    %p.lead= t('about.federation_hint_html', instance: content_tag(:strong, site_hostname))

    .fields-group
      = f.simple_fields_for :account do |account_fields|
        = account_fields.input :username, wrapper: :with_label, label: false, required: true, input_html: { 'aria-label' => t('simple_form.labels.defaults.username'), :autocomplete => 'off', placeholder: t('simple_form.labels.defaults.username') }, append: "@#{site_hostname}", hint: false, disabled: closed_registrations?

      = f.input :email, placeholder: t('simple_form.labels.defaults.email'), required: true, input_html: { 'aria-label' => t('simple_form.labels.defaults.email'), :autocomplete => 'off' }, hint: false, disabled: closed_registrations?
      = f.input :password, placeholder: t('simple_form.labels.defaults.password'), required: true, input_html: { 'aria-label' => t('simple_form.labels.defaults.password'), :autocomplete => 'off' }, hint: false, disabled: closed_registrations?
      = f.input :password_confirmation, placeholder: t('simple_form.labels.defaults.confirm_password'), required: true, input_html: { 'aria-label' => t('simple_form.labels.defaults.confirm_password'), :autocomplete => 'off' }, hint: false, disabled: closed_registrations?

    - if approved_registrations?
      .fields-group
        = f.simple_fields_for :invite_request do |invite_request_fields|
          = invite_request_fields.input :text, as: :text, wrapper: :with_block_label, required: false

    .fields-group
      = f.input :agreement, as: :boolean, wrapper: :with_label, label: t('auth.checkbox_agreement_html', rules_path: about_more_path, terms_path: terms_path), disabled: closed_registrations?

    .actions
      = f.button :button, sign_up_message, type: :submit, class: 'button button-primary', disabled: closed_registrations?

    - if closed_registrations? && @instance_presenter.closed_registrations_message.present?
      .simple_form__overlay-area__overlay
        .simple_form__overlay-area__overlay__content.rich-formatting
          .block-icon= fa_icon 'warning'
          = @instance_presenter.closed_registrations_message.html_safe

app/views/about/more.html.haml
- content_for :page_title do
  = site_hostname

- content_for :header_tags do
  = render partial: 'shared/og'

.grid-3
  .column-0
    .public-account-header.public-account-header--no-bar
      .public-account-header__image
        = image_tag @instance_presenter.hero&.file&.url || @instance_presenter.thumbnail&.file&.url || asset_pack_path('media/images/preview.jpg'), alt: @instance_presenter.site_title, class: 'parallax'

  .column-1
    .landing-page__call-to-action{ dir: 'ltr' }
      .row
        .row__information-board
          .information-board__section
            %span= t 'about.user_count_before'
            %strong= number_with_delimiter @instance_presenter.user_count
            %span= t 'about.user_count_after', count: @instance_presenter.user_count
          .information-board__section
            %span= t 'about.status_count_before'
            %strong= number_with_delimiter @instance_presenter.status_count
            %span= t 'about.status_count_after', count: @instance_presenter.status_count
        .row__mascot
          .landing-page__mascot
            = image_tag @instance_presenter.mascot&.file&.url || asset_pack_path('media/images/elephant_ui_plane.svg'), alt: ''

  .column-2
    .landing-page__information.contact-widget
      %p
        %strong= t 'about.administered_by'

      = account_link_to(@instance_presenter.contact_account)

      - if @instance_presenter.site_contact_email.present?
        %p.contact-widget__mail
          %strong
            = succeed ':' do
              = t 'about.contact'
          %br/
          = mail_to @instance_presenter.site_contact_email, nil, title: @instance_presenter.site_contact_email

  .column-3
    .box-widget
      .rich-formatting= @instance_presenter.site_extended_description.html_safe.presence || t('about.extended_description_html')

app/views/about/show.html.haml
- content_for :page_title do
  = site_hostname

- content_for :header_tags do
  %link{ rel: 'canonical', href: about_url }/
  = render partial: 'shared/og'

.landing
  .landing__brand
    = link_to root_url, class: 'brand' do
      = svg_logo_full
      %span.brand__tagline=t 'about.tagline'

  .landing__grid
    .landing__grid__column.landing__grid__column-registration
      .box-widget
        = render 'registration'

      .directory
        - if Setting.profile_directory
          .directory__tag
            = optional_link_to Setting.profile_directory, explore_path do
              %h4
                = fa_icon 'address-book fw'
                = t('about.discover_users')
                %small= t('about.browse_directory')

              .avatar-stack
                - @instance_presenter.sample_accounts.each do |account|
                  = image_tag current_account&.user&.setting_auto_play_gif ? account.avatar_original_url : account.avatar_static_url, width: 48, height: 48, alt: '', class: 'account__avatar'

        - if Setting.timeline_preview
          .directory__tag
            = optional_link_to Setting.timeline_preview, public_timeline_path do
              %h4
                = fa_icon 'globe fw'
                = t('about.see_whats_happening')
                %small= t('about.browse_public_posts')

        .directory__tag
          = link_to 'https://sinblr.com/@sinblr/102372560413270750', target: '_blank', rel: 'noopener' do
            %h4
              = fa_icon 'tablet fw'
              = t('about.get_apps')
              %small= t('about.apps_platforms')

    .landing__grid__column.landing__grid__column-login
      .box-widget
        = render 'login'

      .hero-widget
        .hero-widget__img
          = image_tag @instance_presenter.hero&.file&.url || @instance_presenter.thumbnail&.file&.url || asset_pack_path('media/images/preview.jpg'), alt: @instance_presenter.site_title

        - if @instance_presenter.site_short_description.present?
          .hero-widget__text
            %p
              = @instance_presenter.site_short_description.html_safe.presence
              = link_to about_more_path do
                = t('about.learn_more')
                = fa_icon 'angle-double-right'

        .hero-widget__footer
          .hero-widget__footer__column
            %h4= t 'about.administered_by'

            = account_link_to @instance_presenter.contact_account

          .hero-widget__footer__column
            %h4= t 'about.server_stats'

            %div{ style: 'display: flex' }
              .hero-widget__counter{ style: 'width: 50%' }
                %strong= number_to_human @instance_presenter.user_count, strip_insignificant_zeros: true
                %span= t 'about.user_count_after', count: @instance_presenter.user_count
              .hero-widget__counter{ style: 'width: 50%' }
                %strong= number_to_human @instance_presenter.active_user_count, strip_insignificant_zeros: true
                %span
                  = t 'about.active_count_after'
                  %abbr{ title: t('about.active_footnote') } *

app/views/about/terms.html.haml
- content_for :page_title do
  = t('terms.title', instance: site_hostname)

.grid
  .column-0
    .box-widget
      .rich-formatting= @instance_presenter.site_terms.html_safe.presence || t('terms.body_html')
  .column-1
    = render 'application/sidebar'